// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.ele.raft;

public interface EntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.Entry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 term = 1;</code>
   */
  int getTerm();

  /**
   * <code>int32 index = 2;</code>
   */
  int getIndex();

  /**
   * <code>int32 commandId = 3;</code>
   */
  int getCommandId();

  /**
   * <code>string command = 4;</code>
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 4;</code>
   */
  com.google.protobuf.ByteString
      getCommandBytes();
}
