// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.ele.raft;

public interface FollowerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.FollowerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool sync = 1;</code>
   */
  boolean getSync();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();
}
