// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.ele.raft;

/**
 * <pre>
 * Follower回应
 * </pre>
 *
 * Protobuf type {@code raft.FollowerReply}
 */
public  final class FollowerReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:raft.FollowerReply)
    FollowerReplyOrBuilder {
  // Use FollowerReply.newBuilder() to construct.
  private FollowerReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FollowerReply() {
    term_ = 0;
    success_ = false;
    matchIndex_ = 0;
    stepDown_ = false;
    suggestNextIndex_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FollowerReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            term_ = input.readInt32();
            break;
          }
          case 16: {

            success_ = input.readBool();
            break;
          }
          case 24: {

            matchIndex_ = input.readInt32();
            break;
          }
          case 32: {

            stepDown_ = input.readBool();
            break;
          }
          case 40: {

            suggestNextIndex_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ele.raft.RaftProto.internal_static_raft_FollowerReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ele.raft.RaftProto.internal_static_raft_FollowerReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ele.raft.FollowerReply.class, com.ele.raft.FollowerReply.Builder.class);
  }

  public static final int TERM_FIELD_NUMBER = 1;
  private int term_;
  /**
   * <code>int32 term = 1;</code>
   */
  public int getTerm() {
    return term_;
  }

  public static final int SUCCESS_FIELD_NUMBER = 2;
  private boolean success_;
  /**
   * <code>bool success = 2;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  public static final int MATCHINDEX_FIELD_NUMBER = 3;
  private int matchIndex_;
  /**
   * <code>int32 matchIndex = 3;</code>
   */
  public int getMatchIndex() {
    return matchIndex_;
  }

  public static final int STEPDOWN_FIELD_NUMBER = 4;
  private boolean stepDown_;
  /**
   * <code>bool stepDown = 4;</code>
   */
  public boolean getStepDown() {
    return stepDown_;
  }

  public static final int SUGGESTNEXTINDEX_FIELD_NUMBER = 5;
  private int suggestNextIndex_;
  /**
   * <code>int32 suggestNextIndex = 5;</code>
   */
  public int getSuggestNextIndex() {
    return suggestNextIndex_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (term_ != 0) {
      output.writeInt32(1, term_);
    }
    if (success_ != false) {
      output.writeBool(2, success_);
    }
    if (matchIndex_ != 0) {
      output.writeInt32(3, matchIndex_);
    }
    if (stepDown_ != false) {
      output.writeBool(4, stepDown_);
    }
    if (suggestNextIndex_ != 0) {
      output.writeInt32(5, suggestNextIndex_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (term_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, term_);
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, success_);
    }
    if (matchIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, matchIndex_);
    }
    if (stepDown_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, stepDown_);
    }
    if (suggestNextIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, suggestNextIndex_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ele.raft.FollowerReply)) {
      return super.equals(obj);
    }
    com.ele.raft.FollowerReply other = (com.ele.raft.FollowerReply) obj;

    boolean result = true;
    result = result && (getTerm()
        == other.getTerm());
    result = result && (getSuccess()
        == other.getSuccess());
    result = result && (getMatchIndex()
        == other.getMatchIndex());
    result = result && (getStepDown()
        == other.getStepDown());
    result = result && (getSuggestNextIndex()
        == other.getSuggestNextIndex());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + getTerm();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + MATCHINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getMatchIndex();
    hash = (37 * hash) + STEPDOWN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getStepDown());
    hash = (37 * hash) + SUGGESTNEXTINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getSuggestNextIndex();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ele.raft.FollowerReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ele.raft.FollowerReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ele.raft.FollowerReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ele.raft.FollowerReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ele.raft.FollowerReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ele.raft.FollowerReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ele.raft.FollowerReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ele.raft.FollowerReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ele.raft.FollowerReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ele.raft.FollowerReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ele.raft.FollowerReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Follower回应
   * </pre>
   *
   * Protobuf type {@code raft.FollowerReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:raft.FollowerReply)
      com.ele.raft.FollowerReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ele.raft.RaftProto.internal_static_raft_FollowerReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ele.raft.RaftProto.internal_static_raft_FollowerReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ele.raft.FollowerReply.class, com.ele.raft.FollowerReply.Builder.class);
    }

    // Construct using com.ele.raft.FollowerReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      term_ = 0;

      success_ = false;

      matchIndex_ = 0;

      stepDown_ = false;

      suggestNextIndex_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ele.raft.RaftProto.internal_static_raft_FollowerReply_descriptor;
    }

    public com.ele.raft.FollowerReply getDefaultInstanceForType() {
      return com.ele.raft.FollowerReply.getDefaultInstance();
    }

    public com.ele.raft.FollowerReply build() {
      com.ele.raft.FollowerReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ele.raft.FollowerReply buildPartial() {
      com.ele.raft.FollowerReply result = new com.ele.raft.FollowerReply(this);
      result.term_ = term_;
      result.success_ = success_;
      result.matchIndex_ = matchIndex_;
      result.stepDown_ = stepDown_;
      result.suggestNextIndex_ = suggestNextIndex_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ele.raft.FollowerReply) {
        return mergeFrom((com.ele.raft.FollowerReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ele.raft.FollowerReply other) {
      if (other == com.ele.raft.FollowerReply.getDefaultInstance()) return this;
      if (other.getTerm() != 0) {
        setTerm(other.getTerm());
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.getMatchIndex() != 0) {
        setMatchIndex(other.getMatchIndex());
      }
      if (other.getStepDown() != false) {
        setStepDown(other.getStepDown());
      }
      if (other.getSuggestNextIndex() != 0) {
        setSuggestNextIndex(other.getSuggestNextIndex());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ele.raft.FollowerReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ele.raft.FollowerReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int term_ ;
    /**
     * <code>int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }
    /**
     * <code>int32 term = 1;</code>
     */
    public Builder setTerm(int value) {
      
      term_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 term = 1;</code>
     */
    public Builder clearTerm() {
      
      term_ = 0;
      onChanged();
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 2;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 2;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 2;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private int matchIndex_ ;
    /**
     * <code>int32 matchIndex = 3;</code>
     */
    public int getMatchIndex() {
      return matchIndex_;
    }
    /**
     * <code>int32 matchIndex = 3;</code>
     */
    public Builder setMatchIndex(int value) {
      
      matchIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 matchIndex = 3;</code>
     */
    public Builder clearMatchIndex() {
      
      matchIndex_ = 0;
      onChanged();
      return this;
    }

    private boolean stepDown_ ;
    /**
     * <code>bool stepDown = 4;</code>
     */
    public boolean getStepDown() {
      return stepDown_;
    }
    /**
     * <code>bool stepDown = 4;</code>
     */
    public Builder setStepDown(boolean value) {
      
      stepDown_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool stepDown = 4;</code>
     */
    public Builder clearStepDown() {
      
      stepDown_ = false;
      onChanged();
      return this;
    }

    private int suggestNextIndex_ ;
    /**
     * <code>int32 suggestNextIndex = 5;</code>
     */
    public int getSuggestNextIndex() {
      return suggestNextIndex_;
    }
    /**
     * <code>int32 suggestNextIndex = 5;</code>
     */
    public Builder setSuggestNextIndex(int value) {
      
      suggestNextIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 suggestNextIndex = 5;</code>
     */
    public Builder clearSuggestNextIndex() {
      
      suggestNextIndex_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:raft.FollowerReply)
  }

  // @@protoc_insertion_point(class_scope:raft.FollowerReply)
  private static final com.ele.raft.FollowerReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ele.raft.FollowerReply();
  }

  public static com.ele.raft.FollowerReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FollowerReply>
      PARSER = new com.google.protobuf.AbstractParser<FollowerReply>() {
    public FollowerReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FollowerReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FollowerReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FollowerReply> getParserForType() {
    return PARSER;
  }

  public com.ele.raft.FollowerReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

