// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.ele.raft;

public interface LeaderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.LeaderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 term = 1;</code>
   */
  int getTerm();

  /**
   * <code>int32 leaderId = 2;</code>
   */
  int getLeaderId();

  /**
   * <code>int32 prevLogIndex = 3;</code>
   */
  int getPrevLogIndex();

  /**
   * <code>int32 prevLogTerm = 4;</code>
   */
  int getPrevLogTerm();

  /**
   * <code>repeated .raft.Entry entries = 5;</code>
   */
  java.util.List<com.ele.raft.Entry> 
      getEntriesList();
  /**
   * <code>repeated .raft.Entry entries = 5;</code>
   */
  com.ele.raft.Entry getEntries(int index);
  /**
   * <code>repeated .raft.Entry entries = 5;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .raft.Entry entries = 5;</code>
   */
  java.util.List<? extends com.ele.raft.EntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .raft.Entry entries = 5;</code>
   */
  com.ele.raft.EntryOrBuilder getEntriesOrBuilder(
      int index);

  /**
   * <code>int32 leaderCommit = 6;</code>
   */
  int getLeaderCommit();
}
