// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.ele.raft;

public interface VoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.VoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 term = 1;</code>
   */
  int getTerm();

  /**
   * <code>int32 candidateId = 2;</code>
   */
  int getCandidateId();

  /**
   * <code>int32 lastLogIndex = 3;</code>
   */
  int getLastLogIndex();

  /**
   * <code>int32 latLogTerm = 4;</code>
   */
  int getLatLogTerm();
}
