// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package com.ele.raft;

/**
 * <pre>
 * 投票请求
 * </pre>
 *
 * Protobuf type {@code raft.VoteRequest}
 */
public  final class VoteRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:raft.VoteRequest)
    VoteRequestOrBuilder {
  // Use VoteRequest.newBuilder() to construct.
  private VoteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VoteRequest() {
    term_ = 0;
    candidateId_ = 0;
    lastLogIndex_ = 0;
    latLogTerm_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private VoteRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            term_ = input.readInt32();
            break;
          }
          case 16: {

            candidateId_ = input.readInt32();
            break;
          }
          case 24: {

            lastLogIndex_ = input.readInt32();
            break;
          }
          case 32: {

            latLogTerm_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ele.raft.RaftProto.internal_static_raft_VoteRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ele.raft.RaftProto.internal_static_raft_VoteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ele.raft.VoteRequest.class, com.ele.raft.VoteRequest.Builder.class);
  }

  public static final int TERM_FIELD_NUMBER = 1;
  private int term_;
  /**
   * <code>int32 term = 1;</code>
   */
  public int getTerm() {
    return term_;
  }

  public static final int CANDIDATEID_FIELD_NUMBER = 2;
  private int candidateId_;
  /**
   * <code>int32 candidateId = 2;</code>
   */
  public int getCandidateId() {
    return candidateId_;
  }

  public static final int LASTLOGINDEX_FIELD_NUMBER = 3;
  private int lastLogIndex_;
  /**
   * <code>int32 lastLogIndex = 3;</code>
   */
  public int getLastLogIndex() {
    return lastLogIndex_;
  }

  public static final int LATLOGTERM_FIELD_NUMBER = 4;
  private int latLogTerm_;
  /**
   * <code>int32 latLogTerm = 4;</code>
   */
  public int getLatLogTerm() {
    return latLogTerm_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (term_ != 0) {
      output.writeInt32(1, term_);
    }
    if (candidateId_ != 0) {
      output.writeInt32(2, candidateId_);
    }
    if (lastLogIndex_ != 0) {
      output.writeInt32(3, lastLogIndex_);
    }
    if (latLogTerm_ != 0) {
      output.writeInt32(4, latLogTerm_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (term_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, term_);
    }
    if (candidateId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, candidateId_);
    }
    if (lastLogIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, lastLogIndex_);
    }
    if (latLogTerm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, latLogTerm_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ele.raft.VoteRequest)) {
      return super.equals(obj);
    }
    com.ele.raft.VoteRequest other = (com.ele.raft.VoteRequest) obj;

    boolean result = true;
    result = result && (getTerm()
        == other.getTerm());
    result = result && (getCandidateId()
        == other.getCandidateId());
    result = result && (getLastLogIndex()
        == other.getLastLogIndex());
    result = result && (getLatLogTerm()
        == other.getLatLogTerm());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + getTerm();
    hash = (37 * hash) + CANDIDATEID_FIELD_NUMBER;
    hash = (53 * hash) + getCandidateId();
    hash = (37 * hash) + LASTLOGINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getLastLogIndex();
    hash = (37 * hash) + LATLOGTERM_FIELD_NUMBER;
    hash = (53 * hash) + getLatLogTerm();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ele.raft.VoteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ele.raft.VoteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ele.raft.VoteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ele.raft.VoteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ele.raft.VoteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ele.raft.VoteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ele.raft.VoteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ele.raft.VoteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ele.raft.VoteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ele.raft.VoteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ele.raft.VoteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 投票请求
   * </pre>
   *
   * Protobuf type {@code raft.VoteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:raft.VoteRequest)
      com.ele.raft.VoteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ele.raft.RaftProto.internal_static_raft_VoteRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ele.raft.RaftProto.internal_static_raft_VoteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ele.raft.VoteRequest.class, com.ele.raft.VoteRequest.Builder.class);
    }

    // Construct using com.ele.raft.VoteRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      term_ = 0;

      candidateId_ = 0;

      lastLogIndex_ = 0;

      latLogTerm_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ele.raft.RaftProto.internal_static_raft_VoteRequest_descriptor;
    }

    public com.ele.raft.VoteRequest getDefaultInstanceForType() {
      return com.ele.raft.VoteRequest.getDefaultInstance();
    }

    public com.ele.raft.VoteRequest build() {
      com.ele.raft.VoteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ele.raft.VoteRequest buildPartial() {
      com.ele.raft.VoteRequest result = new com.ele.raft.VoteRequest(this);
      result.term_ = term_;
      result.candidateId_ = candidateId_;
      result.lastLogIndex_ = lastLogIndex_;
      result.latLogTerm_ = latLogTerm_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ele.raft.VoteRequest) {
        return mergeFrom((com.ele.raft.VoteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ele.raft.VoteRequest other) {
      if (other == com.ele.raft.VoteRequest.getDefaultInstance()) return this;
      if (other.getTerm() != 0) {
        setTerm(other.getTerm());
      }
      if (other.getCandidateId() != 0) {
        setCandidateId(other.getCandidateId());
      }
      if (other.getLastLogIndex() != 0) {
        setLastLogIndex(other.getLastLogIndex());
      }
      if (other.getLatLogTerm() != 0) {
        setLatLogTerm(other.getLatLogTerm());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ele.raft.VoteRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ele.raft.VoteRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int term_ ;
    /**
     * <code>int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }
    /**
     * <code>int32 term = 1;</code>
     */
    public Builder setTerm(int value) {
      
      term_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 term = 1;</code>
     */
    public Builder clearTerm() {
      
      term_ = 0;
      onChanged();
      return this;
    }

    private int candidateId_ ;
    /**
     * <code>int32 candidateId = 2;</code>
     */
    public int getCandidateId() {
      return candidateId_;
    }
    /**
     * <code>int32 candidateId = 2;</code>
     */
    public Builder setCandidateId(int value) {
      
      candidateId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 candidateId = 2;</code>
     */
    public Builder clearCandidateId() {
      
      candidateId_ = 0;
      onChanged();
      return this;
    }

    private int lastLogIndex_ ;
    /**
     * <code>int32 lastLogIndex = 3;</code>
     */
    public int getLastLogIndex() {
      return lastLogIndex_;
    }
    /**
     * <code>int32 lastLogIndex = 3;</code>
     */
    public Builder setLastLogIndex(int value) {
      
      lastLogIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lastLogIndex = 3;</code>
     */
    public Builder clearLastLogIndex() {
      
      lastLogIndex_ = 0;
      onChanged();
      return this;
    }

    private int latLogTerm_ ;
    /**
     * <code>int32 latLogTerm = 4;</code>
     */
    public int getLatLogTerm() {
      return latLogTerm_;
    }
    /**
     * <code>int32 latLogTerm = 4;</code>
     */
    public Builder setLatLogTerm(int value) {
      
      latLogTerm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 latLogTerm = 4;</code>
     */
    public Builder clearLatLogTerm() {
      
      latLogTerm_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:raft.VoteRequest)
  }

  // @@protoc_insertion_point(class_scope:raft.VoteRequest)
  private static final com.ele.raft.VoteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ele.raft.VoteRequest();
  }

  public static com.ele.raft.VoteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VoteRequest>
      PARSER = new com.google.protobuf.AbstractParser<VoteRequest>() {
    public VoteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoteRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VoteRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VoteRequest> getParserForType() {
    return PARSER;
  }

  public com.ele.raft.VoteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

