// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcio.proto

package com.ele.io;

public interface ClientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.ClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string command = 1;</code>
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 1;</code>
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>int32 commandId = 2;</code>
   */
  int getCommandId();
}
