// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcio.proto

package com.ele.io;

public final class ClientProto {
  private ClientProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_ClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_ClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_ServerReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_ServerReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_ResultUnit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_ResultUnit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013rpcio.proto\022\002io\"3\n\rClientRequest\022\017\n\007co" +
      "mmand\030\001 \001(\t\022\021\n\tcommandId\030\002 \001(\005\"F\n\013Server" +
      "Reply\022\017\n\007success\030\001 \001(\010\022\020\n\010redirect\030\002 \001(\010" +
      "\022\024\n\014redirectPort\030\003 \001(\005\"\035\n\nResultUnit\022\017\n\007" +
      "content\030\001 \001(\t2h\n\005RpcIO\022/\n\007Command\022\021.io.C" +
      "lientRequest\032\017.io.ServerReply\"\000\022.\n\005Query" +
      "\022\021.io.ClientRequest\032\016.io.ResultUnit\"\0000\001B" +
      "!\n\ncom.ele.ioB\013ClientProtoP\001\242\002\003CLTb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_ClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_ClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_ClientRequest_descriptor,
        new java.lang.String[] { "Command", "CommandId", });
    internal_static_io_ServerReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_ServerReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_ServerReply_descriptor,
        new java.lang.String[] { "Success", "Redirect", "RedirectPort", });
    internal_static_io_ResultUnit_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_ResultUnit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_ResultUnit_descriptor,
        new java.lang.String[] { "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
