// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcio.proto

package com.ele.io;

public interface ServerReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.ServerReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>bool redirect = 2;</code>
   */
  boolean getRedirect();

  /**
   * <code>int32 redirectPort = 3;</code>
   */
  int getRedirectPort();
}
